# This is a basic workflow to help you get started with Actions

name: CI - demo mulesoft flex-gateway

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

        env:
        # These can be stored in secrets, if desired.
          OPENSHIFT_USER: my-username
          OPENSHIFT_NAMESPACE: my-namespace

      # Runs a set of commands using the runners shell
      - name: Validar YAML
        uses: GrantBirki/json-yaml-validate@v2.6.0
        with:
          files: "./config.yaml"
          comment: "true"

      - name: Mostrar contenido del archivo
        run: cat config.yaml 
      
      - name: Convertir a base 64
        run: 
          cat config.yaml | base64 > config.txt
      
      - name: Mostrar base 64
        run: cat config.txt
      
      - name: Install oc openshift
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
      
      - name: Login cli openshift
        uses: redhat-actions/oc-login@v1
        with:
          
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_username: ${{ secrets.MY_USERNAME }}
          openshift_password: ${{ secrets.MY_USERPASSWORD }}
          insecure_skip_tls_verify: true
      
      
      
          
        

   


        